# Generated by Django 5.2.4 on 2025-08-18 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cbu', models.CharField(max_length=22, null=True, validators=[django.core.validators.RegexValidator(message='El CBU debe contener exactamente 22 dígitos.', regex='^\\d{22}$')])),
                ('cuil', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El CUIL debe contener exactamente 11 dígitos.', regex='^\\d{11}$')])),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Educativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='operativos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_cabecera', models.IntegerField()),
                ('direccion', models.CharField(max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('coordinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabeceras', to='operativos.coordinador')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cabeceras', to='operativos.departamento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cabeceras', to='operativos.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cueanexo', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El Cueanexo debe contener exactamente 9 dígitos.', regex='^\\d{9}$')])),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escuelas', to='operativos.ambito')),
                ('cabecera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas', to='operativos.cabecera')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escuelas', to='operativos.departamento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escuelas', to='operativos.localidad')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escuelas', to='operativos.nivel_educativo')),
                ('sistema_gestion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escuelas', to='operativos.sistema_gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Operativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Aprender Censal Primaria', 'Aprender Censal Primaria'), ('Aprender Censal Secundaria', 'Aprender Censal Secundaria'), ('Aprender Muestral Primaria', 'Aprender Muestral Primaria'), ('Aprender Muestral Secundaria', 'Aprender Muestral Secundaria')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('año_lectivo', models.CharField(max_length=4)),
                ('estado', models.BooleanField(default=True)),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operativos', to='operativos.nivel_educativo')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='material/')),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='operativos.operativo')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='fotos_de_operativos/')),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='operativos.operativo')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Estadisticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_total', models.IntegerField()),
                ('presentes_total', models.IntegerField()),
                ('escuelas_total', models.IntegerField()),
                ('escuelas_retiraron_total', models.IntegerField()),
                ('secciones_total', models.IntegerField()),
                ('aplicadores_total', models.IntegerField()),
                ('veedores_total', models.IntegerField()),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_estadisticos', to='operativos.operativo')),
            ],
        ),
        migrations.AddField(
            model_name='coordinador',
            name='operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinadores', to='operativos.operativo'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabeceras', to='operativos.operativo'),
        ),
        migrations.CreateModel(
            name='Aplicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cuil', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El CUIL debe contener exactamente 11 dígitos.', regex='^\\d{11}$')])),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aplicadores', to='operativos.ambito')),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicadores', to='operativos.operativo')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=2)),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Mañana extendida', 'Mañana extendida'), ('Tarde extendida', 'Tarde extendida'), ('Jornada completa', 'Jornada completa'), ('Jornada extendida', 'Jornada extendida'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')])),
                ('matricula', models.IntegerField()),
                ('aplicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones', to='operativos.aplicador')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='operativos.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Cruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('aplicador_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces_aplicador_dos', to='operativos.aplicador')),
                ('aplicador_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces_aplicador_uno', to='operativos.aplicador')),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces', to='operativos.operativo')),
                ('seccion_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces_seccion_dos', to='operativos.seccion')),
                ('seccion_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces_seccion_uno', to='operativos.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Veedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('Rector', 'Rector'), ('Director', 'Director'), ('Personal a cargo', 'Personal a cargo')])),
                ('cuil', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El CUIL debe contener exactamente 11 dígitos.', regex='^\\d{11}$')])),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veedores', to='operativos.operativo')),
            ],
        ),
        migrations.AddField(
            model_name='escuela',
            name='veedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas', to='operativos.veedor'),
        ),
    ]
