# Generated by Django 5.2.4 on 2025-08-18 18:48

from django.db import migrations

DEPARTAMENTOS = [
    "Aguirre", "Alberdi", "Atamisqui", "Avellaneda", "Banda",
    "Belgrano", "Capital", "Choya", "Copo", "Figueroa",
    "General Taboada", "Guasayán", "Jiménez", "Juan Felipe Ibarra",
    "Loreto", "Mitre", "Moreno", "Ojo de Agua", "Pellegrini",
    "Quebrachos", "Rio Hondo", "Rivadavia", "Robles", "Salavina",
    "San Martín", "Sarmiento", "Silípica",
]

def forward(apps, schema_editor):
    Departamento = apps.get_model("operativos", "Departamento")
    for nombre in DEPARTAMENTOS:
        Departamento.objects.get_or_create(nombre=nombre)
    # Alternativa más rápida en lotes grandes:
    # objs = [Departamento(nombre=n) for n in DEPARTAMENTOS]
    # Departamento.objects.bulk_create(objs, ignore_conflicts=True)

def reverse(apps, schema_editor):
    # Reversa segura: no borrar (evita romper FKs si ya hay datos relacionados)
    # Si QUERÉS permitir rollback, cambiá a un delete filtrado:
    # Departamento = apps.get_model("operativos", "Departamento")
    # Departamento.objects.filter(nombre__in=DEPARTAMENTOS).delete()
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("operativos", "0001_seed_departamentos"),  # asegúrate que apunte a la migración que crea Departamento
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
