# Generated by Django 5.2.4 on 2025-08-18 18:51

from django.db import migrations


NIVELES_EDUCATIVOS = [
    'Nivel Primario', 'Nivel Secundario'
]


def forward(apps, schema_editor):
    Nivel_educativo = apps.get_model("operativos", "Nivel_Educativo")
    for nivel in NIVELES_EDUCATIVOS:
        Nivel_educativo.objects.get_or_create(nombre=nivel)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0003_seed_localidades'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)
    ]
