# Generated by Django 5.2.4 on 2025-08-18 18:52

from django.db import migrations


SISTEMAS_GESTION = [
    'Estatal', 'Privada'
]


def forward(apps, schema_editor):
    Sistema_gestion = apps.get_model("operativos", "Sistema_Gestion")
    for sistema_gestion in Sistema_gestion:
        Sistema_gestion.objects.get_or_create(nombre=sistema_gestion)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0004_seed_niveles_educativos'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)
    ]
