# Generated by Django 5.2.4 on 2025-08-18 18:52

from django.db import migrations


AMBITOS = [
    'Rural', 'Urbano'
]


def forward(apps, schema_editor):
    Ambitos = apps.get_model("operativos", "Ambito")
    for amb in AMBITOS:
        Ambitos.objects.get_or_create(nombre=amb)
    

def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0005_seed_sistemas_gestion'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)
    ]
