# Generated by Django 5.2.4 on 2025-08-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0005_seed_sistemas_gestion'),
    ]

    operations = [
    ]
