# Generated by Django 5.2.4 on 2025-08-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0006_seed_ambitos'),
    ]

    operations = [
    ]
